FROM r-base
RUN R -e "install.packages('data.table',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('PRROC',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('glmnet',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('dplyr',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('tidyr',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('foreach',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('doParallel',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('ranger',dependencies=TRUE, repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('rbenchmark',dependencies=TRUE, repos='http://cran.rstudio.com/')"
WORKDIR /usr/src/app
COPY . .
CMD ["myscript.R"]
ENTRYPOINT ["Rscript"]

